# Generated by Django 3.0.8 on 2020-08-02 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mps', '0001_initial'),
        ('senators', '0001_initial'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='mp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mps.Mps'),
        ),
        migrations.AddField(
            model_name='vote',
            name='senator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='senators.Senators'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
