# Generated by Django 3.0.8 on 2020-08-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20200802_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='location',
            new_name='location_ip',
        ),
        migrations.AddField(
            model_name='vote',
            name='latitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='locale',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='longitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
