# Generated by Django 3.0.8 on 2020-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20200802_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='location_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
