# Generated by Django 3.0.8 on 2020-08-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20200802_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='region',
        ),
        migrations.AddField(
            model_name='vote',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
