# Generated by Django 3.0.8 on 2020-08-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_vote_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
